require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicationsController do

  # This should return the minimal set of attributes required to create a valid
  # Publication. As you add validations to Publication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all publications as @publications" do
      publication = Publication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:publications).should eq([publication])
    end
  end

  describe "GET show" do
    it "assigns the requested publication as @publication" do
      publication = Publication.create! valid_attributes
      get :show, {:id => publication.to_param}, valid_session
      assigns(:publication).should eq(publication)
    end
  end

  describe "GET new" do
    it "assigns a new publication as @publication" do
      get :new, {}, valid_session
      assigns(:publication).should be_a_new(Publication)
    end
  end

  describe "GET edit" do
    it "assigns the requested publication as @publication" do
      publication = Publication.create! valid_attributes
      get :edit, {:id => publication.to_param}, valid_session
      assigns(:publication).should eq(publication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Publication" do
        expect {
          post :create, {:publication => valid_attributes}, valid_session
        }.to change(Publication, :count).by(1)
      end

      it "assigns a newly created publication as @publication" do
        post :create, {:publication => valid_attributes}, valid_session
        assigns(:publication).should be_a(Publication)
        assigns(:publication).should be_persisted
      end

      it "redirects to the created publication" do
        post :create, {:publication => valid_attributes}, valid_session
        response.should redirect_to(Publication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publication as @publication" do
        # Trigger the behavior that occurs when invalid params are submitted
        Publication.any_instance.stub(:save).and_return(false)
        post :create, {:publication => { "user" => "invalid value" }}, valid_session
        assigns(:publication).should be_a_new(Publication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Publication.any_instance.stub(:save).and_return(false)
        post :create, {:publication => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publication" do
        publication = Publication.create! valid_attributes
        # Assuming there are no other publications in the database, this
        # specifies that the Publication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Publication.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => publication.to_param, :publication => { "user" => "" }}, valid_session
      end

      it "assigns the requested publication as @publication" do
        publication = Publication.create! valid_attributes
        put :update, {:id => publication.to_param, :publication => valid_attributes}, valid_session
        assigns(:publication).should eq(publication)
      end

      it "redirects to the publication" do
        publication = Publication.create! valid_attributes
        put :update, {:id => publication.to_param, :publication => valid_attributes}, valid_session
        response.should redirect_to(publication)
      end
    end

    describe "with invalid params" do
      it "assigns the publication as @publication" do
        publication = Publication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Publication.any_instance.stub(:save).and_return(false)
        put :update, {:id => publication.to_param, :publication => { "user" => "invalid value" }}, valid_session
        assigns(:publication).should eq(publication)
      end

      it "re-renders the 'edit' template" do
        publication = Publication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Publication.any_instance.stub(:save).and_return(false)
        put :update, {:id => publication.to_param, :publication => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publication" do
      publication = Publication.create! valid_attributes
      expect {
        delete :destroy, {:id => publication.to_param}, valid_session
      }.to change(Publication, :count).by(-1)
    end

    it "redirects to the publications list" do
      publication = Publication.create! valid_attributes
      delete :destroy, {:id => publication.to_param}, valid_session
      response.should redirect_to(publications_url)
    end
  end

end
