require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RespectsController do

  # This should return the minimal set of attributes required to create a valid
  # Respect. As you add validations to Respect, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RespectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all respects as @respects" do
      respect = Respect.create! valid_attributes
      get :index, {}, valid_session
      assigns(:respects).should eq([respect])
    end
  end

  describe "GET show" do
    it "assigns the requested respect as @respect" do
      respect = Respect.create! valid_attributes
      get :show, {:id => respect.to_param}, valid_session
      assigns(:respect).should eq(respect)
    end
  end

  describe "GET new" do
    it "assigns a new respect as @respect" do
      get :new, {}, valid_session
      assigns(:respect).should be_a_new(Respect)
    end
  end

  describe "GET edit" do
    it "assigns the requested respect as @respect" do
      respect = Respect.create! valid_attributes
      get :edit, {:id => respect.to_param}, valid_session
      assigns(:respect).should eq(respect)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Respect" do
        expect {
          post :create, {:respect => valid_attributes}, valid_session
        }.to change(Respect, :count).by(1)
      end

      it "assigns a newly created respect as @respect" do
        post :create, {:respect => valid_attributes}, valid_session
        assigns(:respect).should be_a(Respect)
        assigns(:respect).should be_persisted
      end

      it "redirects to the created respect" do
        post :create, {:respect => valid_attributes}, valid_session
        response.should redirect_to(Respect.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved respect as @respect" do
        # Trigger the behavior that occurs when invalid params are submitted
        Respect.any_instance.stub(:save).and_return(false)
        post :create, {:respect => { "user" => "invalid value" }}, valid_session
        assigns(:respect).should be_a_new(Respect)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Respect.any_instance.stub(:save).and_return(false)
        post :create, {:respect => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested respect" do
        respect = Respect.create! valid_attributes
        # Assuming there are no other respects in the database, this
        # specifies that the Respect created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Respect.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => respect.to_param, :respect => { "user" => "" }}, valid_session
      end

      it "assigns the requested respect as @respect" do
        respect = Respect.create! valid_attributes
        put :update, {:id => respect.to_param, :respect => valid_attributes}, valid_session
        assigns(:respect).should eq(respect)
      end

      it "redirects to the respect" do
        respect = Respect.create! valid_attributes
        put :update, {:id => respect.to_param, :respect => valid_attributes}, valid_session
        response.should redirect_to(respect)
      end
    end

    describe "with invalid params" do
      it "assigns the respect as @respect" do
        respect = Respect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Respect.any_instance.stub(:save).and_return(false)
        put :update, {:id => respect.to_param, :respect => { "user" => "invalid value" }}, valid_session
        assigns(:respect).should eq(respect)
      end

      it "re-renders the 'edit' template" do
        respect = Respect.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Respect.any_instance.stub(:save).and_return(false)
        put :update, {:id => respect.to_param, :respect => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested respect" do
      respect = Respect.create! valid_attributes
      expect {
        delete :destroy, {:id => respect.to_param}, valid_session
      }.to change(Respect, :count).by(-1)
    end

    it "redirects to the respects list" do
      respect = Respect.create! valid_attributes
      delete :destroy, {:id => respect.to_param}, valid_session
      response.should redirect_to(respects_url)
    end
  end

end
